# create a k8s service for the httpserver with port 8080
apiVersion: v1
kind: Service
metadata:
  name:  httpserver-service
spec:
  selector:
    app:  httpserver
  type:   ClusterIP 
  ports:
  - name:  http
    port:  8080
    targetPort:  8080


