apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: dontry/httpserver:0.2.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 2
          # graceful shutdown
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh","-c","kill -SIGTERM $(pidof go-app)" ]


